language: python
python:
  - "3.7"
  - "pypy3"  
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py sdist
  - pip install dist/*.tar.gz
# command to run tests
script: pytest --cov-report term-missing --cov=pyspark_expectations tests/